### ISSUE TITLE
No client-side rendering

### ISSUE THREAD

**Issue by stepanh** [CrocoDillon/universal-react-redux-boilerplate#12] opened 2016-09-12 06:43 UTC
You say 'client-side rendering is an enhancement', but I think I'm not the only one who would appreciate it to be enabled by default.

Right now, clicking through blog, every page gets server re-rendered.

Keep up the good work  ;-)

**Comment by CrocoDillon** [comment] 2016-09-12 07:18
> enabled by default

It should be, of course! :astonished: I'll take a look tonight. What platform are you on?

**Comment by stepanh** [comment] 2016-09-12 07:32
cheers :-)

macOS, Node 6.5.0, Chrome

**Comment by CrocoDillon** [comment] 2016-09-12 19:13
Works for me, on Ubuntu though with Node 6.2.1. Can you try the `v2` branch? It's basically same as `master` minus the Windows compatibility fixes.

I tried both development and production modes, client side rendering worked on both. There is some network activity when navigating trough the “blog” but those are just data fetches.

**Comment by CrocoDillon** [comment] 2016-09-20 09:04
I'll re-open this when I get more information to work from :)

**Comment by jonaswindey** [comment] 2016-10-21 09:47
I have the same issue

Running locally gives a first 404 error in console on 
`GET http://localhost:3000/app.js 404 (Not Found)`

However, once the page is loaded, I can access http://localhost:3000/app.js and see the full script.

Chrome on macOS, node v6.3.1

**Comment by jonaswindey** [comment] 2016-10-21 09:52
Extra info: 
- in production mode the client-side script is loaded correctly.
- in dev mode, I get the following error:
  `[webpack-isomorphic-tools] [error] `.development()` method is now deprecated (for server-side instance only, not for webpack plugin instance) and has no effect. Set up a proper `process.env.NODE_ENV` variable instead.`

**Comment by CrocoDillon** [comment] 2016-10-21 10:27
Thanks for the details!

Not sure those issues are related but it's something I should look at either way. The deprecation warning is easy to fix, just remove the [`.development(...)`](https://github.com/CrocoDillon/universal-react-redux-boilerplate/blob/c6fd20f1bec88b93f4702c1375a6d2463d9f0606/bin/server#L25) line. It relies on `NODE_ENV` already anyway.

Could you try that and see if it solves the client-side script issues too? Otherwise I will take a look in the weekend.

**Comment by jonaswindey** [comment] 2016-10-21 13:06
I've removed the .development line in /bin/server but the problem is still there.

What's strange is that in my chrome I get `GET http://localhost:3000/app.js 404 (Not Found)`, but once the page is loaded the same get works correctly.

**Comment by CrocoDillon** [comment] 2016-10-21 15:54
I found out the issue is related to changes in [`webpack-dev-middleware` 1.8.0](https://github.com/webpack/webpack-dev-middleware/compare/v1.7.0...v1.8.0)... my bad probably, since it's not made for Koa.

While I figure out how to make it work again with Koa I suggest:

``` json
"webpack-dev-middleware": "1.7.0"
```

**Comment by CrocoDillon** [comment] 2016-10-21 16:02
By the way, this is somewhat related (it will fix the root cause of this issue, which is the workaround needed to make Webpack dev middleware work with Koa) and might be an interesting thread to follow - webpack/webpack-dev-middleware#111

**Comment by Truji92** [comment] 2016-10-22 14:05
The problem seems to be that the middleware serves the bundle correctly but with a 404 status code. I "fixed" it in webpack.server.js adding:

`if (mockResponse) {
      res.statusCode = 200
    }`

here is the full file https://gist.github.com/Truji92/1e598ceab3c967d2dbed140ec739483d

Maybe is a ugly fix, but it's working... haha

**Comment by CrocoDillon** [comment] 2016-12-04 15:54
I pinned `webpack-dev-middleware` to`1.7.0` on master for now, so closing this issue. Need more time to look into the real issue anyway 😁

**Closed as completed by CrocoDillon** 2016-12-04 15:54 UTC
